### PR TITLE
fixes #267: include filenames in checksums

### LINKED ISSUE #267: Timestamp checksums do not work when renaming a single file
When I rename a single resource file (in IDEA or in Explorer), then the name changes but the modification time of the file does not change. Then the (incremental) `compile` task does not start...

To solve this, we could include the filename in the checksum calculation.
To make it even more reliable, we could also include the file size.

What do you think?

### PR DESCRIPTION
**Pull request by DevCharly**

### CODE REVIEW

File: modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/Md5.kt [hunk 1]
```diff
@@ -24,7 +24,7 @@ public class Md5 {
          * a checksum of the last modified timestamp.
          */
         fun toMd5Directories(filesOrDirectories: List<File>,
-                toBytes: (File) -> ByteArray = { it.lastModified().toString().toByteArray() } ): String? {
+                toBytes: (File) -> ByteArray = { "${it.path} ${it.lastModified()} ${it.length()}".toByteArray() } ): String? {
```
Comment (cbeust) [inline modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/Md5.kt]: Isn't `length()` superfluous? (doesn't matter much, just curious what you have in mind)
